/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface":                  "#15121b",
        "surface-dim":              "#15121b",
        "surface-bright":           "#3b3742",
        "surface-container-lowest": "#0f0d15",
        "surface-container-low":    "#1d1a23",
        "surface-container":        "#211e27",
        "surface-container-high":   "#2c2832",
        "surface-container-highest":"#37333d",
        "on-surface":               "#e7e0ed",
        "on-surface-variant":       "#cbc3d7",
        "inverse-surface":          "#e7e0ed",
        "inverse-on-surface":       "#322f39",
        "outline":                  "#958ea0",
        "outline-variant":          "#494454",
        "surface-tint":             "#d0bcff",
        "surface-variant":          "#37333d",
        "primary":                  "#d0bcff",
        "on-primary":               "#3c0091",
        "primary-container":        "#a078ff",
        "on-primary-container":     "#340080",
        "primary-fixed":            "#e9ddff",
        "primary-fixed-dim":        "#d0bcff",
        "on-primary-fixed":         "#23005c",
        "on-primary-fixed-variant": "#5516be",
        "inverse-primary":          "#6d3bd7",
        "secondary":                "#4cd7f6",
        "on-secondary":             "#003640",
        "secondary-container":      "#03b5d3",
        "on-secondary-container":   "#00424e",
        "secondary-fixed":          "#acedff",
        "secondary-fixed-dim":      "#4cd7f6",
        "on-secondary-fixed":       "#001f26",
        "on-secondary-fixed-variant":"#004e5c",
        "tertiary":                 "#ffb869",
        "on-tertiary":              "#482900",
        "tertiary-container":       "#ca801e",
        "on-tertiary-container":    "#3f2300",
        "tertiary-fixed":           "#ffdcbb",
        "tertiary-fixed-dim":       "#ffb869",
        "on-tertiary-fixed":        "#2c1700",
        "on-tertiary-fixed-variant":"#673d00",
        "error":                    "#ffb4ab",
        "on-error":                 "#690005",
        "error-container":          "#93000a",
        "on-error-container":       "#ffdad6",
        "background":               "#15121b",
        "on-background":            "#e7e0ed",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg":      "0.5rem",
        "xl":      "0.75rem",
        "2xl":     "1rem",
        "full":    "9999px",
      },
      spacing: {
        "xs":          "4px",
        "sm":          "8px",
        "md":          "16px",
        "lg":          "24px",
        "xl":          "32px",
        "gutter":      "16px",
        "edge_margin": "20px",
        "unit":        "4px",
      },
      fontFamily: {
        "space":    ["Space Grotesk", "sans-serif"],
        "inter":    ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-caps":     ["12px",  { lineHeight: "16px",  letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-lg":    ["30px",  { lineHeight: "36px",  fontWeight: "700" }],
        "display-numeric":["42px",  { lineHeight: "48px",  letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md":    ["24px",  { lineHeight: "32px",  fontWeight: "600" }],
        "body-lg":        ["18px",  { lineHeight: "28px",  fontWeight: "400" }],
        "body-md":        ["16px",  { lineHeight: "24px",  fontWeight: "400" }],
        "body-sm":        ["14px",  { lineHeight: "20px",  fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};